module.exports = {
  AntDesign: require('./AntDesign.ttf'),
  Entypo: require('./Entypo.ttf'),
  EvilIcons: require('./EvilIcons.ttf'),
  Feather: require('./Feather.ttf'),
  FontAwesome: require('./FontAwesome.ttf'),
  FontAwesome5: require('./FontAwesome5_Solid.ttf'),
  FontAwesome6: require('./FontAwesome6_Solid.ttf'),
  Foundation: require('./Fontisto.ttf'),
  Foundation: require('./Foundation.ttf'),
  Ionicons: require('./Ionicons.ttf'),
  Lucide: require('./Lucide.ttf'),
  MaterialCommunityIcons: require('./MaterialCommunityIcons.ttf'),
  MaterialIcons: require('./MaterialIcons.ttf'),
  SimpleLineIcons: require('./SimpleLineIcons.ttf'),
  Octicons: require('./Octicons.ttf'),
  Zocial: require('./Zocial.ttf'),
};